---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core==2.20.0
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
  python_interpreter:
    package_system: "python314"
    python_path: "/usr/bin/python3.14"

images:
  base_image:
     name: fedora:43

additional_build_steps:
  prepend_base:
     - RUN dnf install -y dnf-plugins-core
     - RUN dnf install -y python3.14
     - RUN dnf install -y python3.14-devel
     - RUN python3.14 -m ensurepip
  prepend_final: |
    RUN whoami
    RUN cat /etc/os-release
  append_final:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc
    - RUN ansible-galaxy collection list
    - RUN pip3 list
    - RUN ansible --version
