---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.0
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

images:
  base_image:
     name: quay.io/centos/centos:stream9

additional_build_steps:
  prepend_base:
     - RUN dnf install -y epel-release epel-next-release
  prepend_final: |
    RUN whoami
    RUN cat /etc/os-release
  append_final:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc

