---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.0rc1
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"

images:
  base_image:
     name: quay.io/centos/centos:stream9

additional_build_steps:
  prepend_base:
     - RUN dnf install -y epel-release epel-next-release
     - RUN dnf install -y dnf-plugins-core
     - RUN dnf install -y python3-devel
     - RUN dnf install -y python3.11
     - RUN dnf install -y python3.11-devel
     - RUN python3.11 -m ensurepip
  prepend_final: |
    RUN whoami
    RUN cat /etc/os-release
  append_final:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc
    - RUN ansible-galaxy collection list
    - RUN pip3 list
