---
collections:
  - name: awx.awx
  - name: amazon.aws
  - name: openstack.cloud
  - name: community.vmware
  - name: community.general
  - name: community.docker
  - name: community.grafana
  - name: kubernetes.core
