---
collections:
  - name: awx.awx
  - name: amazon.aws
  #  - name: openstack.cloud
  - name: community.vmware
  - name: community.general
  - name: community.docker
  - name: community.grafana
  - name: community.crypto
  - name: community.mysql
  - name: community.windows
  - name: kubernetes.core
  - name: ansible.netcommon
  - name: junipernetworks.junos
  - name: juniper.device
  - name: ansible.posix
  - name: ansible.windows
  - name: freeipa.ansible_freeipa
  - name: community.sops
  - name: gluster.gluster
  - name: cisco.nxos
  - name: cisco.ios
  - name: fortinet.fortios
  - name: fortinet.fortimanager
  - name: community.hashi_vault
  - name: cyberark.conjur
  - name: containers.podman
  - name: netapp.ontap
  - name: damhau.ansible_for_nsxt
