name: build EE
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build EE
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-builder

      - name: Build EE
        run: ansible-builder build -v3 -t docker.io/cwollinger/awx-ee:2.12 --container-runtime=docker

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push EE
        run: docker push docker.io/cwollinger/awx-ee:2.12
